defaults:
  - _self_
  - dataset: CelebA
  - optional experimental: None
    
gpu: 0 # Choose GPU, -1 for CPU.

tb_name:
    string_base: 
    hp_base: {type: train.train_type}
    string_extra: 
    hp_extra: 
    
redirect: true # redirect output to log
detect_anomaly: false

augmentation:
  train_exclude: H   # H to exclude CIFAR, CEDA11 to exclude CEDA high conf samples.
  autoaugment: true
  hflip: true
  crop: 4

architecture:
  arch_style: RN
  file_path: ~

train:
  expfolder: ~
  tb_folder: default
  batch_size: 128
  use_adam: false
  train_type: plain
 
  eps: 0.01
  
  momentum: 0.9
  
  in_loss_type: ce
  out_loss_type: ce
  
  schedule:
    lr_schedule_type: constant
    lr_schedule: [.1, .1, 0.01, 0.001, 0.0001]
    lr_schedule_epochs: [1, 50, 75, 90, 100]
    
    kappa_schedule_type: constant
    kappa_schedule: [0., 0.01]
    kappa_schedule_epochs: [10,  100]
    
    eps_schedule_type: constant
    eps_schedule: [0.01]
    eps_schedule_epochs: [100]
    
    weight_decay: 0.0005
    
eval:
  eps: 0.01
  batch_size: 100
  