# @package _global_ 

dset_in_name: CelebA
dset_out_name: TINY

architecture:
  dset_in_name: CelebA
  num_classes: 2
  
train:
  schedule:
    lr_schedule_type: constant
    # lr_schedule: [0.1, 0.01, 0.001, .0001]
    # lr_schedule_epochs: [50, 75, 90, 100]
    lr_schedule: [0.1, 0.01, 0.001, .0001]
    lr_schedule_epochs: [3, 5, 8, 10]
