# @package _global_ 


architecture:
  arch_style: densenet

train:
  train_type: plain
  
  in_loss_type: ce
  out_loss_type: oe
  
  schedule:   
    kappa_schedule_type: constant
    kappa_schedule: [1.]
    kappa_schedule_epochs: [100]
    
    weight_decay: 0.0005
    
    lr_schedule_type: constant
    lr_schedule: [0.1, 0.01, 0.001, .0001]
    lr_schedule_epochs: [50, 75, 90, 100]
    
tb_name:
    string_base: 
    hp_base: {type: train.train_type}
    string_extra: 
    hp_extra: 